name: systemweit
favicon: null
layout_spectrum: 0.8669064848218113
typography_spectrum: 0.22825278132222593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.42313485173508525
  lightness: 0.028559941332787275
  saturation: 0.8583854243624955
  rhythmicContrast: 0.6565576593857259
purpose: []
